step 10
andriimikhaylovskiy/spring.boot pull request #11
Opened 2024-06-19 20:30 UTC by andriimikhaylovskiy

2024-06-20 05:53 UTC, Elena-Bruyako requested changes
Your build was failed

2024-06-22 13:46 UTC, sarakhmen requested changes
good job but let's slightly improve your solution :)

2024-06-22 13:46 UTC, sarakhmen commented on pom.xml
> +			<version>10.15.0</version>
do you really need this dependency?

2024-06-22 13:46 UTC, sarakhmen commented on src/main/java/mate/academy/spring/boot/repository/BookRepository.java
> +    List<Book> findAllByCategorySet_Id(@Param("categoryId") Long categoryId, Pageable pageable);
please follow Java's method naming convention

2024-06-22 13:46 UTC, sarakhmen commented on src/main/java/mate/academy/spring/boot/service/BookServiceImpl.java
> +    //private final CategoryRepository categoryRepo;
remove commented field

2024-06-24 06:11 UTC, Elena-Bruyako approved these changes
Good job!

2024-06-26 07:16 UTC, merged