Step2
andriimikhaylovskiy/spring.boot pull request #2
Opened 2024-03-20 17:59 UTC by andriimikhaylovskiy

2024-03-20 19:04 UTC, olekskov requested changes

2024-03-20 19:04 UTC, olekskov commented on src/main/java/mate/academy/spring/boot/controller/BookController.java
> +@RequestMapping("/api/books")
Better to move api to application.properties as global prefix in order not to mention it in every controller
```suggestion
@RequestMapping("/books")
```

2024-03-20 19:04 UTC, olekskov commented on src/main/java/mate/academy/spring/boot/dto/CreateBookRequestDto.java
> +    }
Why do we need Lombok in dependencies if we don't use it?

2024-03-20 19:04 UTC, olekskov commented on src/main/java/mate/academy/spring/boot/service/BookServiceImpl.java
> +    }
Please do not include methods without implementation

2024-03-21 20:06 UTC, okuzan requested changes

2024-03-21 20:06 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/controller/BookController.java
> +
```suggestion
```

2024-03-21 20:06 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/dto/CreateBookRequestDto.java
> +    }
use @ Data annotation

2024-03-21 20:06 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/model/Book.java
> +@Entity
it's not advisable to use @Data with entities, they can have side effects, if you don't implement equals and hashcode by yourself

2024-03-21 20:06 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/service/BookServiceImpl.java
> +
```suggestion
```

2024-03-22 17:57 UTC, okuzan requested changes

2024-03-22 17:57 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/model/Book.java
> +@EqualsAndHashCode
the problem with data is that it includes this annotation, so you didn't resolve the problem
if you don't need equals at this point, just remove it

2024-03-22 19:20 UTC, okuzan approved these changes

2024-03-24 10:54 UTC, merged