first attempt
andriimikhaylovskiy/spring.boot pull request #3
Opened 2024-03-30 19:28 UTC by andriimikhaylovskiy

2024-03-31 12:04 UTC, okuzan requested changes

2024-03-31 12:04 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/model/Book.java
> +@Where(clause = "is_deleted=false")
deprecated, use sqlRestriction

2024-03-31 12:04 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/model/Book.java
> +@Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE book SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction("is_deleted = FALSE")
```

2024-03-31 12:04 UTC, okuzan commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +      author: mateacademy
don't mention mateacademy in this project, use your username

2024-04-01 08:19 UTC, Vasul-Pankiv approved these changes

2024-04-01 15:48 UTC, merged