Step8
andriimikhaylovskiy/spring.boot pull request #9
Opened 2024-06-06 18:40 UTC by andriimikhaylovskiy

2024-06-06 20:11 UTC, Vasul-Pankiv requested changes

2024-06-06 20:11 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/spring/boot/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```

2024-06-06 20:11 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/spring/boot/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
fix it everywhere

2024-06-07 18:49 UTC, Elena-Bruyako requested changes
Looks good, let's fix some comments

2024-06-07 18:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/BookServiceImpl.java
> +        if (requestDto.isbn() == null || requestDto.isbn().isBlank()) {
Does CreateBookRequestDto have some validations for isbn field like NotBlank? 
Also, your Book entity should has constraint for isbn like nullable = false and unique = true
Check these please, and remove redundant logic if needed

2024-06-07 18:49 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01_1-insert-default-book.yaml
> +                  value: '1.99'
```suggestion
                  value: '1.99'
                  
```

2024-06-07 18:49 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01_1-insert-default-book.yaml
> +                  value: '1.99'
Add empty line in the end for all changelogs

2024-06-08 11:04 UTC, Vasul-Pankiv approved these changes

2024-06-09 17:16 UTC, merged